services:
  caddy:
    image: caddy:2.9.1
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    networks:
      oauth-labs:
        aliases:
          - server-00.oauth.labs
          - client-00.oauth.labs
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./docker/caddy/config:/config
      - ./docker/caddy/data:/data

  db:
    image: mariadb:11.4.3-noble
    volumes:
      - ./docker/db/init.prod.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/mysql
    networks:
      - oauth-labs
    secrets:
      - db_root_password
    environment:
      MARIADB_ROOT_PASSWORD_FILE: '/var/run/secrets/db_root_password'

  valkey:
    image: valkey/valkey:8.0.1-alpine
    networks:
      - oauth-labs

  server-00:
    environment:
      LAB_VARIANT: ${LAB_VARIANT:-fixed}
    build:
      context: .
      dockerfile: ./docker/Dockerfile.baselab
      args:
        LAB_NUMBER: '00'
        COMPONENT: server
    depends_on:
      - caddy
      - db
      - valkey
    volumes:
      - ./docker/lab00/server.config.yaml:/app/config.yaml
    networks:
      - oauth-labs
    cpus: 1
    mem_limit: 1g

  client-00:
    environment:
      LAB_VARIANT: ${LAB_VARIANT:-fixed}
    build:
      context: .
      dockerfile: ./docker/Dockerfile.baselab
      args:
        LAB_NUMBER: '00'
        COMPONENT: client
    depends_on:
      - caddy
      - db
      - valkey
      - server-00
    volumes:
      - ./docker/lab00/client.config.yaml:/app/config.yaml
    networks:
      - oauth-labs
    cpus: 1
    mem_limit: 1g

secrets:
  db_root_password:
    file: ./docker/db/root_password.prod.txt

networks:
  oauth-labs:

volumes:
  db-data:
